apiVersion: v1
entries:
  applications:
  - apiVersion: v2
    appVersion: "16.0"
    created: "2024-04-03T11:19:00.629172842+01:00"
    description: A Helm chart for Kubernetes
    digest: 89c07183d1b308b3e0bb8493692e434b1d9a46c010d29acf41457f95c4f764a6
    name: applications
    type: application
    urls:
    - applications-16.0.tgz
    version: "16.0"
  - apiVersion: v2
    appVersion: "15.0"
    created: "2024-04-03T11:19:00.628826085+01:00"
    description: A Helm chart for Kubernetes
    digest: aad6075c6c017505332d2ea2a0dccf7a2ba1b82f04cd7abfa77c4a6800167f7f
    name: applications
    type: application
    urls:
    - applications-15.0.tgz
    version: "15.0"
  - apiVersion: v2
    appVersion: "14.0"
    created: "2024-04-03T11:19:00.628482985+01:00"
    description: A Helm chart for Kubernetes
    digest: d8d4aa42f0f79e30a2d5385702c8af7516481f05bc7bce078c7c4cbe52925b71
    name: applications
    type: application
    urls:
    - applications-14.0.tgz
    version: "14.0"
  - apiVersion: v2
    appVersion: "13.0"
    created: "2024-04-03T11:19:00.627929019+01:00"
    description: A Helm chart for Kubernetes
    digest: c25e8b2fadba38cba02c51b8376e8f5ebb101edd7d9f41d168548f8d0da601f4
    name: applications
    type: application
    urls:
    - applications-13.0.tgz
    version: "13.0"
  - apiVersion: v2
    appVersion: "11.0"
    created: "2024-04-03T11:19:00.627527954+01:00"
    description: A Helm chart for Kubernetes
    digest: afc1dd81cf1eab3a8a42720040610ad9203889f115d37eb9fc29b1d61ade74cb
    name: applications
    type: application
    urls:
    - applications-11.tgz
    version: "11"
  - apiVersion: v2
    appVersion: "11.0"
    created: "2024-04-03T11:19:00.627121263+01:00"
    description: A Helm chart for Kubernetes
    digest: c52d51234b8d09c7428cae3907ed75563ec894fc6f3660ffdb076e6f70520cc9
    name: applications
    type: application
    urls:
    - applications-11.0.tgz
    version: "11.0"
  - apiVersion: v2
    appVersion: "10.0"
    created: "2024-04-03T11:19:00.626735493+01:00"
    description: A Helm chart for Kubernetes
    digest: d776aa384a49eebe6c0792b909a5060ad838070cc254306b993cd470d132503b
    name: applications
    type: application
    urls:
    - applications-10.tgz
    version: "10"
  - apiVersion: v2
    appVersion: "9.0"
    created: "2024-04-03T11:19:00.631220316+01:00"
    description: A Helm chart for Kubernetes
    digest: 3306f321a4fce7bb982151928a47e979cd1759fcf5df4f4789bb7cd6c014dbd5
    name: applications
    type: application
    urls:
    - applications-9.tgz
    version: "9"
  - apiVersion: v2
    appVersion: "8.0"
    created: "2024-04-03T11:19:00.630925143+01:00"
    description: A Helm chart for Kubernetes
    digest: 696dfc69f18f7135d6a817650a1fe80fdd8dd195b9b80b3b329b226cfe3580c7
    name: applications
    type: application
    urls:
    - applications-8.tgz
    version: "8"
  - apiVersion: v2
    appVersion: "7.0"
    created: "2024-04-03T11:19:00.6305387+01:00"
    description: A Helm chart for Kubernetes
    digest: 41adca58e1c6cac2510a06f9a2c2922638e7c8c879ba39b456a6838df816189d
    name: applications
    type: application
    urls:
    - applications-7.tgz
    version: "7"
  - apiVersion: v2
    appVersion: "6.0"
    created: "2024-04-03T11:19:00.630166994+01:00"
    description: A Helm chart for Kubernetes
    digest: 0a668243e0efb2d41f4727bf710e1140727fa7cbd1b75a53f06e0ba538d1c961
    name: applications
    type: application
    urls:
    - applications-6.tgz
    version: "6"
  - apiVersion: v2
    appVersion: "5.0"
    created: "2024-04-03T11:19:00.629867756+01:00"
    description: A Helm chart for Kubernetes
    digest: 91087f2a4e64cff549103101ee65e7e507ebab14f351b40233dba17ef4da1e15
    name: applications
    type: application
    urls:
    - applications-5.tgz
    version: "5"
  - apiVersion: v2
    appVersion: "3.0"
    created: "2024-04-03T11:19:00.629520685+01:00"
    description: A Helm chart for Kubernetes
    digest: f2000281505d5c58318c698a9a5088e967dd5ec9ef00806ded8a30673a7d3b19
    name: applications
    type: application
    urls:
    - applications-3.tgz
    version: "3"
generated: "2024-04-03T11:19:00.626020586+01:00"
